# Generated by Django 3.2.15 on 2022-09-25 16:23

import currency_converter.currencies.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3, unique=True, validators=[currency_converter.currencies.validators.validate_currency_symbol], verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Open rate')),
                ('high', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='High rate')),
                ('low', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Low rate')),
                ('close', models.DecimalField(decimal_places=10, max_digits=17, verbose_name='Close rate')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.currency', verbose_name='Source currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='currencies.currency', verbose_name='Target currency')),
            ],
            options={
                'verbose_name': 'Currency rate',
                'verbose_name_plural': 'Currencies rate',
                'ordering': ('-date',),
            },
        ),
    ]
