version: '3'

volumes:
  currency_converter_local_mysql_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: currency_converter_local_django
    container_name: currency_converter_local_django

    depends_on:
      - mysql
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
    command: /start

  celeryworker:
    <<: *django
    image: currency_converter_local_celeryworker
    container_name: currency_converter_local_celeryworker
    depends_on:
      - mysql
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: currency_converter_celerybeat
    container_name: currency_converter_local_celerybeat
    depends_on:
      - mysql
      - redis
    ports: []
    command: /start-celerybeat

  mysql:
    image: mysql:8.0
    container_name: currency_converter_local_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - currency_converter_local_mysql_data:/var/lib/mysql:Z
    env_file:
      - ./.envs/.local/.mysql

  redis:
    image: redis:6
    container_name: currency_converter_local_redis
